language: go
cache:
  directories:
    - ${GOPATH}/src/github.com/${TRAVIS_REPO_SLUG}/vendor
    - ${GOPATH}/src/github.com/h12w
    - ${GOPATH}/src/github.com/Masterminds    
    - ${GOPATH}/src/github.com/mattn
go: 1.6
sudo: false

env:
    CI_SERVICE=travis-ci

install:
  - go get -v github.com/h12w/gosweep
  - go get -v github.com/mattn/goveralls
  - go get -v github.com/Masterminds/glide
  - glide install

script:
  - go test -v ./...
  - pwd
  - ls -lha

after_success:
  - bash ${GOPATH}/src/github.com/h12w/gosweep/gosweep.sh
