language: go
cache:
  directories:
    - ${GOPATH}/src/github.com/${TRAVIS_REPO_SLUG}/vendor
    - ${GOPATH}/src/github.com/fzipp
    - ${GOPATH}/src/github.com/h12w
    - ${GOPATH}/src/github.com/mattn
    - ${GOPATH}/src/golang/dep
go:
  - tip
  - 1.9
  - 1.8
sudo: false

env:
    CI_SERVICE=travis-ci

install:
  - go get -v -u github.com/client9/misspell/cmd/misspell
  - go get -v -u github.com/fzipp/gocyclo
  - go get -v -u github.com/h12w/gosweep
  - go get -v -u github.com/mattn/goveralls
  - go get -v -u github.com/golang/dep/cmd/dep
  - dep ensure

script:
  - bash ${GOPATH}/src/github.com/h12w/gosweep/gosweep.sh
